### ISSUE TITLE
How start installation? 

### ISSUE THREAD

**Issue by alejandri** [gregoryduckworth/laravel-multi-auth#1]
Hi. Great repo tutorial. How start installation? Any doc or link for start. Thanks

**Comment by gregoryduckworth** [comment]
Hi,

No documentation as of yet, but I'll put together something soon.

As for installation, clone the repo, run composer install and then copy a new env file. I'll put that into the new documentation as well.

**Comment by gregoryduckworth** [comment]
I've added some basic documentation now in 3201b7e.

Let me know if you think I've missed anything.

**Comment by Mixpeal** [comment]
Its says:

1/1 FatalErrorException in User.php line 8: Cannot declare class App\Models\User because the name is already in use

```
in User.php line 8
```

when trying to register admin/register
pls how can i solve this? thanks in advance

**Comment by gregoryduckworth** [comment]
@Mixpeal - I've updated the user model file in the commit 2d87b7a9c48ce130cabcd1422591ac6e510a8e8e which should solve the issue.

Let me know if it doesn't.

**Comment by Mixpeal** [comment]
@gregoryduckworth
Thanks a million, it works you really save me, God bless you, pls can u drop your facebook profile link

**Comment by Mixpeal** [comment]
pls help, i am unable to get an authenticated user , how will i do that

**Comment by gregoryduckworth** [comment]
@Mixpeal - are you getting any error of any sort? Does anything appear in the logs at all?
